### ISSUE TITLE
Update copy and logic on the chapter 1 completion screen

### ISSUE THREAD

**Issue by GBKS** [saving-satoshi/saving-satoshi#186]
There was nothing about hashes in chapter 1, so the text is not accurate. We also can't continue in the content, since the demo has only one chapter. I can come up with an updated design and copy in Figma to implement. Ideally, we can ask learners about their feedback at this point. Would also be great if we can get them to subscribe or follow in one way or another to let them know when new content is available.

![savingsatoshi com_en_chapters_chapter-1_done](https://user-images.githubusercontent.com/695901/220911538-1cb4e76d-f85d-4f6e-bd25-68c641bb44f8.png)

**Comment by ecurrencyhodler** [comment]
Related to https://github.com/saving-satoshi/saving-satoshi/issues/176 with regards to a call to action after completion.

**Comment by afterburn** [comment]
Please leave a link to the final copy here, and assign this issue to either me or someone else who wants to implement the changes once final copy is ready @ecurrencyhodler.

**Comment by ecurrencyhodler** [comment]
I think this will get included in @GBKS work once screens are finalized. I'll assign to him for now.

**Comment by ecurrencyhodler** [comment]
This is being addressed in https://github.com/saving-satoshi/saving-satoshi/pull/263

**Comment by benalleng** [comment]
Master should now match [Figma](https://www.figma.com/file/LqjK3Tpvd9KJ4buFArCJBQ/Saving-Satoshi?node-id=2374%3A25039&t=5w4Okp9P4CQ0l3mS-0) 
The TopBar however, is still not quite like the design as it is not fully transparent.

**Comment by ecurrencyhodler** [comment]
Closed by #263
